---
title: "hb trends"
author: "Timo Asikainen"
date: "2025-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-packages}
# install.packages('moments')
library(dplyr)
library(lubridate)
library(tidyr)
library(moments)
```
```{r load-data}
load('C:/git_repot/DATA/donationdata.fortimo.rdata')
```


```{r load-and-process-data}
simple = donationdata$donation
simple = left_join(simple,donationdata$donor[,c('releaseID','DateOfBirth','Sex','BloodGroup')],by='releaseID')
simple$age= as.numeric(difftime(simple$DonationDate,simple$DateOfBirth),unit="weeks")/52.25
simple$month = as.factor(month(simple$DonationDate))
simple$year = year(simple$DonationDate)
simple$year.factor = as.factor(simple$year)

date0 = simple %>%
  group_by(releaseID) %>%
  summarise(date0=min(DonationDate),.groups='drop')

donation0 = simple %>%
  inner_join(date0,join_by(x$DonationDate==y$date0,releaseID))

# repeat donations
donation.r = simple %>%
  left_join(cbind(date0,sent=1),join_by(x$DonationDate==y$date0,releaseID)) %>%
  filter(is.na(sent)) %>%
  select(-sent) %>%
  mutate(month=as.integer(month))

# mr=lm(Hb~0+month,data=donation.r)
# summary(mr) # Nämä olisi varmaankin saanut myös suoraan keskiarvoina

seasonal = donation.r %>%
  group_by(month) %>%
  summarise(seasonal=mean(Hb,na.rm=TRUE),.groups='drop') %>%
  mutate(month=as.integer(month))
# The mutation above used to be in different context

# repeat donations (?)
donation.r = inner_join(donation.r,seasonal,join_by(month))

# donation0$year=year(donation0$DonationDate)
# donation0$year.factor=as.factor(donation0$year)
```

```{r function-definitions}
plotHbDist = function(data0,sex,cutoff,zoom=TRUE) {
  sex0=data0[data0$year>=2005&data0$Sex==sex&!is.na(data0$Hb)&data0$BloodDonationTypeKey %in% c('Whole Blood (K)','No Donation (E)'),c('Hb')]  
  freq = sex0 %>%
    group_by(Hb) %>%
    summarise(n=n()) %>%
    mutate(prop=n/sum(n))

  limits = NULL
  if (zoom)
    limits = c(cutoff-5,cutoff+5)
  plot(prop~Hb,data=freq,type='l',lwd=2,xlim=limits)
  # freq.all %>% filter(Hb>=130,Hb<140)

  mean0=mean(sex0$Hb)
  sd0=sd(sex0$Hb)
  
  ndist=dnorm(unique(freq$Hb),mean=mean0,sd=sd0)
  lines(unique(freq$Hb),ndist)
  abline(v=cutoff,col='blue')
  
  return(list(mean0=mean0,sd0=sd0))
}

estimateTrend = function(final) {
  final.longer = matToLonger(final)
  final.longer$interceptFemale=1
  final.longer$interceptFemale[final.longer$Sex=='Male']=0
  final.longer$interceptMale=1-final.longer$interceptFemale
  m=lm(value~0+interceptFemale+interceptMale+year:Sex,data=final.longer)
  print(summary(m))
  return(m)
}

matToLonger = function(mat) {
  df1=as.data.frame(pivot_longer(cbind(Sex=rownames(mat)[1:2],mat[1:2,]),colnames(mat),names_to='year'))
  df1$year=as.integer(df1$year)
  return(df1)
}

plotYearSex = function(m,relative=FALSE) {
  cofs = summary(m)$coeff
  conames=rownames(cofs)
  codf=data.frame(name=conames,estimate=cofs[,1])
  wh=grep('(Male|Female)',conames)
  codf$Sex[wh]=sub('.*(Male|Female).*','\\1',conames[wh])
  wh=grep('[0-9][0-9][0-9][0-9]',conames)
  codf$year[wh]=sub('[^0-9]+([0-9]+).*','\\1',conames[wh])
  codf=cbind(codf,confint(m))
  
  codf=codf[!is.na(codf$year),]
  pah=pivot_wider(codf,names_from='year',values_from='estimate',id_cols=c('Sex'))
  rn = as.vector(pah[,1])
  pah=as.data.frame(pah[,-1])
  rownames(pah)=rn$Sex
  
  means=apply(pah,1,mean)
  if (!relative)
    means=0*means
  
  pah=pah-means
  
  pah2=pivot_wider(codf,names_from='year',values_from='2.5 %',id_cols=c('Sex'))
  pah2=as.data.frame(pah2[,-1])
  pah2=pah2-means
  pah3=pivot_wider(codf,names_from='year',values_from='97.5 %',id_cols=c('Sex'))
  pah3=as.data.frame(pah3[,-1])
  pah3=pah3-means
  
  pah.all=rbind(pah,pah2,pah3)
  
  matplot(t(pah.all),type='l',lty=c(rep('solid',2),rep('dashed',4)),col=rep(c('red','blue'),2),axes=FALSE)
  axis(2)
  axis(side=1,at=1:ncol(pah.all),labels=colnames(pah.all))
  return(pah.all)
}
```

```{r}
m=lm(0+Hb~age+Sex+seasonal+year.factor:Sex,data=donation.r[donation.r$year>=2005,])
sm=summary(m)
r.mat=plotYearSex(m)
adjustment=pivot_longer(cbind(Sex=rownames(r.mat)[1:2],r.mat[1:2,]),colnames(r.mat),names_to='year') # ,names_to='Sex',values_to='value')
adjustment$year=as.integer(adjustment$year)

str(seasonal)
seasonal$month=as.integer(seasonal$month)
str(adjustment)
str(donation0)
```


```{r}
# compute the adjusted data for first-time donations (?):
# substract the unexplained effect (year x sex) estimated from 
donation0a = donation0 %>%
  mutate(month = as.integer(month)) %>%
  inner_join(seasonal,join_by(month)) %>%
  inner_join(adjustment,join_by(Sex,year)) %>%
  mutate(Hb.adj = Hb - value)

donation0a$month.factor=as.factor(donation0a$month)

summary(donation0a)

# adjusted model
m=lm(Hb.adj~0+Sex+age+year.factor:Sex+seasonal,data=donation0a[donation0a$year>=2005,])
sm=summary(m)
final=plotYearSex(m,relative=TRUE)
estimateTrend(final)
apply(final,1,min)
apply(final,1,max)

# unadjusted data
m=lm(Hb~0+age+Sex+year.factor:Sex,data=donation0[donation0$year>=2005,])
summary(m)
final=plotYearSex(m,relative=TRUE)
estimateTrend(final)
```


```{r}
# annual = cbind(t(r.mat["Male",]),t(r.mat["Female",]))

donation0$year=year(donation0$DonationDate)

# donation0$year.factor = as.factor(donation0$year)
str(donation0$year.factor)

# Regressiomalleja

m=lm(Hb~age+Sex+year,data=donation0)
summary(m)

m=lm(0+Hb~age+Sex+Sex:year,data=donation0)
summary(m)

m=lm(0+Hb~age+Sex+year.factor:Sex,data=donation0[donation0$year>=2005,])
# m=lm(0+Hb~age+year.factor:Sex,data=donation0)
summary(m)
sm=summary(m)
# plot(sm$coeff[4:nrow(sm$co),1])

m=lm(Hb~year,data=donation0)
summary(m)
```

```{r}
hmm = simple %>%
  filter(Sex=='Male') %>%
  mutate(referred=(Hb<135),on.boundary=(Hb==135)) %>%
  group_by(year) %>%
  summarise(n=n(),n.referred=sum(referred,na.rm=TRUE),n.boundary=sum(on.boundary,na.rm=TRUE)) %>%
  mutate(prop=n.referred/n,ratio=n.referred/n.boundary)
plot(n.referred~year,data=hmm,type='l',lwd=3)
plot(prop~year,data=hmm,type='l',lwd=3)
plot(ratio~year,data=hmm,type='l',lwd=3,main='ratio of number referred to number at boundary (male/135)')

simple %>%
  group_by(BloodDonationTypeKey) %>%
  summarise(n())

str(simple)

```


```{r}

# hist(male0$Hb)

plotHbDist(simple,'Male',135,FALSE)
plotHbDist(simple,'Male',135,TRUE)
plotHbDist(simple,'Female',125,FALSE)
plotHbDist(simple,'Female',125,TRUE)
```

```{r distribution-analysis}
data0=simple
sex='Male'
cutoff=135
  sex0=data0[data0$year>=2005&data0$Sex==sex&!is.na(data0$Hb)&data0$BloodDonationTypeKey %in% c('Whole Blood (K)','No Donation (E)'),c('Hb')]  
  freq = sex0 %>%
    group_by(Hb) %>%
    summarise(n=n()) %>%
    mutate(prop=n/sum(n))

  
    # qqnorm(data0$Hb)
  # stest =data0 %>% filter(sex=='Male',year==2010) %>% select(Hb) 
  # qqnorm(stest$Hb)

  mean0=mean(sex0$Hb)
  sd0=sd(sex0$Hb)

  # Käsittelemätön jakauma
  plot(prop~Hb,data=freq,type='l',lwd=2,xlim=NULL)
  
  # Estimoituja keskiarvoa ja -hajontaa vastaava normaalijakauma
  Hb.values = unique(freq$Hb)
  ndist=dnorm(Hb.values,mean=mean0,sd=sd0)
  lines(unique(freq$Hb),ndist)
  
  # Erotuskuvaaja, tämä ei ole kovin tärkeä mutta sama tietysti ottaa mukaan
  plot(freq$prop-ndist~Hb.values)
  abline(v=cutoff,col='blue')
  abline(h=c(-1,1)*0.0005,col='red')

  cnt = 0
  freq2 = freq
  k = which(freq$Hb==cutoff) 
  while (TRUE) {
    diff = (freq2$prop-ndist)[1:(k-1)]
    wh = which(diff < -0.0005)
    if (length(wh) == 0)
      break
    wh0 = max(wh)
    ds0 = diff[wh0]
    
    diff.plus = (freq2$prop-ndist)[k:nrow(freq2)]
    wh = which(diff.plus > 0.0005)
    if (length(wh) == 0)
      break
    wh1 = min(wh)
    ds1 = diff.plus[wh1]
    
    to.adjust = min(-ds0,ds1)
    
    freq2$prop[wh0] = freq2$prop[wh0] + to.adjust
    freq2$prop[wh1+(k-1)] = freq2$prop[wh1+(k-1)] - to.adjust
    
    print(paste(wh0,':',ds0,':',wh1+(k-1),':',ds1,'=>',to.adjust))
    
    cnt = cnt + 1
    if (cnt > 1000) {
      print('max iterations exceeded (back-stop)')
      break
    }
  }

  mean1=  freq2 %>% 
      mutate(mom=Hb*prop) %>%
      summarise(mean=sum(mom))
  mean1=as.numeric(mean1)
  sd1 =  freq2 %>% 
      mutate(mom=(Hb-as.numeric(mean1))^2*prop) %>%
      summarise(sdx=sum(mom)) 
  sd1=sqrt(as.numeric(sd1))

  plot(prop~Hb,data=freq2,type='l',lwd=2,xlim=NULL)
  ndist2=dnorm(Hb.values,mean=mean1,sd=sd1)
  lines(Hb.values,ndist2,col='green')
  abline(v=cutoff,col='blue',lty='dashed')
  rect(mean1-5,0,mean1+5,0.001,col='pink',ldw=2)
  abline(v=mean1,lty='dotted',lwd=3)
```

```{r}
# These have been copied to the chunk above
mean1=  freq2 %>% 
    mutate(mom=Hb*prop) %>%
    summarise(mean=sum(mom))
mean1-mean0
mean1=as.numeric(mean1)
sd1 =  freq2 %>% 
    mutate(mom=(Hb-as.numeric(mean1))^2*prop) %>%
    summarise(sdx=sum(mom)) 
sd1=sqrt(as.numeric(sd1))
sd1-sd0
```


```{r}
donation0 %>% filter(Hb<135,Sex=='Male')

skewness(freq$n)
shapiro.test(freq$n)

```


```{r normal-distribution-parameter-testing}
vavg=155
stdev=11

diff=seq(-5,2,0.1)
y=pnorm(135+diff,mean=avg,sd=stdev)
wh0=which(diff==0) 
y=y/y[wh0]
plot(y~diff,xlab='difference in mean',ylab=paste0('ratio between mean+diff and mean=',avg))
abline(v=0,lty='dashed')

diff=seq(-1,3,0.05)
y=pnorm(135,mean=avg,sd=stdev+diff)
wh0=which(diff==0)
y=y/y[wh0]
plot(y~diff,xlab='difference in stdev',ylab=paste0('ratio between stdev+diff and stdev=',stdev))
abline(v=0,lty='dashed')
# Riippuvuus ei ole lineaarinen
# abline(a=y[wh0],b=(y[length(y)]-y[1])/(diff[length(diff)]-diff[1]))
```
